original_titles = [
  {"13-assassins-2010", %{original: "十三人の刺客", transliteration: "", translation: ""}},
  {"20th-century-boys-1-the-beginning-of-the-end-2008",
   %{original: "本格科学冒険映画 20世紀少年 第1章 終わりの始まり", transliteration: "", translation: ""}},
  {"20th-century-boys-2-the-last-hope-2009",
   %{original: "本格科学冒険映画 20世紀少年 第2章 最後の希望", transliteration: "", translation: ""}},
  {"20th-century-boys-3-redemption",
   %{original: "本格科学冒険映画 20世紀少年 最終章 ぼくらの旗", transliteration: "", translation: ""}},
  {"adventure-of-kigan-castle-1966", %{original: "奇巌城の冒険", transliteration: "", translation: ""}},
  {"adventures-of-zatoichi-1964", %{original: "座頭市関所破り", transliteration: "", translation: ""}},
  {"akira-1988", %{original: "アキラ", transliteration: "", translation: ""}},
  {"alive-2003", %{original: "ALIVE", transliteration: "", translation: ""}},
  {"all-monsters-attack-1969",
   %{original: "ゴジラ・ミニラ・ガバラ オール怪獣大進撃", transliteration: "", translation: ""}},
  {"all-round-appraiser-q-the-eyes-of-mona-lisa-2014",
   %{original: "万能鑑定士Q -モナ・リザの瞳-", transliteration: "", translation: ""}},
  {"always-sunset-on-third-street-2-2007",
   %{original: "ALWAYS 続・三丁目の夕日", transliteration: "", translation: ""}},
  {"always-sunset-on-third-street-2005",
   %{original: "ALWAYS 三丁目の夕日", transliteration: "", translation: ""}},
  {"always-sunset-on-third-street-3-2012",
   %{original: "ALWAYS 三丁目の夕日'64", transliteration: "", translation: ""}},
  {"aragami-2003", %{original: "荒神", transliteration: "", translation: ""}},
  {"assassination-classroom-2015", %{original: "暗殺教室", transliteration: "", translation: ""}},
  {"assassination-classroom-graduation-2016",
   %{original: "暗殺教室〜卒業編〜", transliteration: "", translation: ""}},
  {"assault-girls-2009", %{original: "ASSAULT GIRLS", transliteration: "", translation: ""}},
  {"atragon-1963", %{original: "海底軍艦", transliteration: "", translation: ""}},
  {"attack-on-titan-2015", %{original: "進撃の巨人", transliteration: "", translation: ""}},
  {"attack-on-titan-end-of-the-world-2015",
   %{original: "進撃の巨人 エンド オブ ザ ワールド", transliteration: "", translation: ""}},
  {"avalon-2001", %{original: "アヴァロン", transliteration: "", translation: ""}},
  {"azumi-2-death-or-love-2005",
   %{original: "あずみ2 Death or Love", transliteration: "", translation: ""}},
  {"azumi-2003", %{original: "あずみ", transliteration: "", translation: ""}},
  {"ballad-2009", %{original: "BALLAD 名もなき恋のうた", transliteration: "", translation: ""}},
  {"battle-in-outer-space-1959", %{original: "宇宙大戦争", transliteration: "", translation: ""}},
  {"battle-royale-2000", %{original: "バトル・ロワイアル", transliteration: "", translation: ""}},
  {"battle-royale-ii-requiem-2003",
   %{original: "バトル・ロワイアルII 【鎮魂歌】", transliteration: "", translation: ""}},
  {"bullet-train-1975", %{original: "新幹線大爆破", transliteration: "", translation: ""}},
  {"casshern-2004", %{original: "CASSHERN", transliteration: "", translation: ""}},
  {"castle-in-the-sky-1986", %{original: "天空の城ラピュタ", transliteration: "", translation: ""}},
  {"conflagration-1975", %{original: "東京湾炎上", transliteration: "", translation: ""}},
  {"crossfire-2000", %{original: "クロスファイア", transliteration: "", translation: ""}},
  {"daigoro-vs-goliath-1972",
   %{original: "怪獣大奮戦 ダイゴロウ対ゴリアス", transliteration: "", translation: ""}},
  {"daimajin-1966", %{original: "大魔神", transliteration: "", translation: ""}},
  {"daredevil-in-the-castle-1961", %{original: "大坂城物語", transliteration: "", translation: ""}},
  {"death-note-2006", %{original: "デスノート", transliteration: "", translation: ""}},
  {"death-note-light-up-the-new-world-2016",
   %{original: "デスノート Light up the NEW world", transliteration: "", translation: ""}},
  {"death-note-the-last-name-2006",
   %{original: "デスノート the Last name", transliteration: "", translation: ""}},
  {"destroy-all-monsters-1968", %{original: "怪獣総進撃", transliteration: "", translation: ""}},
  {"dogora-1964", %{original: "宇宙大怪獣ドゴラ", transliteration: "", translation: ""}},
  {"dororo-2007", %{original: "どろろ", transliteration: "", translation: ""}},
  {"ebirah-horror-of-the-deep-1966",
   %{original: "ゴジラ・エビラ・モスラ 南海の大決闘", transliteration: "", translation: ""}},
  {"eko-eko-azarak-ii-birth-of-the-wizard-1996",
   %{original: "エコエコアザラクII -BIRTH OF THE WIZARD-", transliteration: "", translation: ""}},
  {"eko-eko-azarak-iii-misa-the-dark-angel-1998",
   %{original: "エコエコアザラクIII -MISA THE DARK ANGEL-", transliteration: "", translation: ""}},
  {"eko-eko-azarak-wizard-of-darkness-1995",
   %{original: "エコエコアザラク -WIZARD OF DARKNESS-", transliteration: "", translation: ""}},
  {"espy-1974", %{original: "エスパイ", transliteration: "", translation: ""}},
  {"eternal-zero-2013", %{original: "永遠の0", transliteration: "", translation: ""}},
  {"evil-of-dracula-1974", %{original: "血を吸う薔薇", transliteration: "", translation: ""}},
  {"fight-zatoichi-fight-1964", %{original: "座頭市血笑旅", transliteration: "", translation: ""}},
  {"frankenstein-conquers-the-world-1965",
   %{original: "フランケンシュタイン対地底怪獣", transliteration: "", translation: ""}},
  {"friends-naki-on-monster-island-2011",
   %{original: "friends もののけ島のナキ", transliteration: "", translation: ""}},
  {"fueled-the-man-they-called-pirate-2016",
   %{original: "海賊とよばれた男", transliteration: "", translation: ""}},
  {"g-i-samurai-1979", %{original: "戦国自衛隊", transliteration: "", translation: ""}},
  {"gamera-2-attack-of-legion-1996", %{original: "ガメラ2 レギオン襲来", transliteration: "", translation: ""}},
  {"gamera-3-revenge-of-iris-1999", %{original: "ガメラ3 邪神〈イリス〉覚醒", transliteration: "", translation: ""}},
  {"gamera-guardian-of-the-universe-1995", %{original: "ガメラ 大怪獣空中決戦", transliteration: "", translation: ""}},
  {"gamera-super-monster-1980", %{original: "宇宙怪獣ガメラ", transliteration: "", translation: ""}},
  {"gamera-the-brave-2006", %{original: "小さき勇者たち〜ガメラ〜", transliteration: "", translation: ""}},
  {"gamera-the-giant-monster-1965", %{original: "大怪獣ガメラ", transliteration: "", translation: ""}},
  {"gamera-vs-barugon-1966", %{original: "大怪獣決闘 ガメラ対バルゴン", transliteration: "", translation: ""}},
  {"gamera-vs-guiron-1969", %{original: "ガメラ対大悪獣ギロン", transliteration: "", translation: ""}},
  {"gamera-vs-gyaos-1967", %{original: "大怪獣空中戦 ガメラ対ギャオス", transliteration: "", translation: ""}},
  {"gamera-vs-jiger-1970", %{original: "ガメラ対大魔獣ジャイガー", transliteration: "", translation: ""}},
  {"gamera-vs-viras-1968", %{original: "ガメラ対宇宙怪獣バイラス", transliteration: "", translation: ""}},
  {"gamera-vs-zigra-1971", %{original: "ガメラ対深海怪獣ジグラ", transliteration: "", translation: ""}},
  {"gantz-2011", %{original: "GANTZ", transliteration: "", translation: ""}},
  {"gantz-perfect-answer-2011", %{original: "GANTZ PERFECT ANSWER", transliteration: "", translation: ""}},
  {"gatchaman-2013", %{original: "ガッチャマン", transliteration: "", translation: ""}},
  {"genghis-khan-to-the-ends-of-the-earth-and-sea-2007",
   %{original: "蒼き狼 地果て海尽きるまで", transliteration: "", translation: ""}},
  {"genocide-1968", %{original: "昆虫大戦争", transliteration: "", translation: ""}},
  {"ghidorah-the-three-headed-monster-1964",
   %{original: "三大怪獣 地球最大の決戦", transliteration: "", translation: ""}},
  {"ghost-in-the-shell-1995", %{original: "GHOST IN THE SHELL / 攻殻機動隊", transliteration: "", translation: ""}},
  {"glorious-team-batista-2008", %{original: "チーム・バチスタの栄光", transliteration: "", translation: ""}},
  {"gods-left-hand-devils-right-hand-2006",
   %{original: "神の左手悪魔の右手", transliteration: "", translation: ""}},
  {"godzilla-1954", %{original: "ゴジラ", transliteration: "", translation: ""}},
  {"godzilla-2000-millennium-1999", %{original: "ゴジラ2000 ミレニアム", transliteration: "", translation: ""}},
  {"godzilla-against-mechagodzilla-2002", %{original: "ゴジラ×メカゴジラ", transliteration: "", translation: ""}},
  {"godzilla-final-wars-2004", %{original: "ゴジラ FINAL WARS", transliteration: "", translation: ""}},
  {"godzilla-mothra-and-king-ghidorah-giant-monsters-all-out-attack-2001",
   %{original: "ゴジラ・モスラ・キングギドラ 大怪獣総攻撃", transliteration: "", translation: ""}},
  {"godzilla-raids-again-1955", %{original: "ゴジラの逆襲", transliteration: "", translation: ""}},
  {"godzilla-tokyo-sos-2003", %{original: "ゴジラ×モスラ×メカゴジラ 東京SOS", transliteration: "", translation: ""}},
  {"godzilla-vs-biollante-1989", %{original: "ゴジラvsビオランテ", transliteration: "", translation: ""}},
  {"godzilla-vs-destoroyah-1995", %{original: "ゴジラvsデストロイア", transliteration: "", translation: ""}},
  {"godzilla-vs-gigan-1972", %{original: "地球攻撃命令 ゴジラ対ガイガン", transliteration: "", translation: ""}},
  {"godzilla-vs-hedorah-1971", %{original: "ゴジラ対ヘドラ", transliteration: "", translation: ""}},
  {"godzilla-vs-king-ghidorah-1991", %{original: "ゴジラvsキングギドラ", transliteration: "", translation: ""}},
  {"godzilla-vs-mechagodzilla-1974", %{original: "ゴジラ対メカゴジラ", transliteration: "", translation: ""}},
  {"godzilla-vs-mechagodzilla-ii-1993", %{original: "ゴジラvsメカゴジラ", transliteration: "", translation: ""}},
  {"godzilla-vs-megaguirus-2000", %{original: "ゴジラ×メガギラス G消滅作戦", transliteration: "", translation: ""}},
  {"godzilla-vs-megalon-1973", %{original: "ゴジラ対メガロ", transliteration: "", translation: ""}},
  {"godzilla-vs-mothra-1992", %{original: "ゴジラvsモスラ", transliteration: "", translation: ""}},
  {"godzilla-vs-spacegodzilla-1994", %{original: "ゴジラvsスペースゴジラ", transliteration: "", translation: ""}},
  {"goemon-2009", %{original: "GOEMON", transliteration: "", translation: ""}},
  {"goke-body-snatcher-from-hell-1968", %{original: "吸血鬼ゴケミドロ", transliteration: "", translation: ""}},
  {"golden-bat-1966", %{original: "黄金バット", transliteration: "", translation: ""}},
  {"gorath-1962", %{original: "妖星ゴラス", transliteration: "", translation: ""}},
  {"gunhed-1989", %{original: "ガンヘッド", transliteration: "", translation: ""}},
  {"h-man-1958", %{original: "美女と液体人間", transliteration: "", translation: ""}},
  {"hara-kiri-death-of-a-samurai-2011", %{original: "一命", transliteration: "", translation: ""}},
  {"hidden-fortress-1958", %{original: "隠し砦の三悪人", transliteration: "", translation: ""}},
  {"hidden-fortress-the-last-princess-2008",
   %{original: "隠し砦の三悪人 THE LAST PRINCESS", transliteration: "", translation: ""}},
  {"high-and-low-1963", %{original: "天国と地獄", transliteration: "", translation: ""}},
  {"howls-moving-castle-2004", %{original: "ハウルの動く城", transliteration: "", translation: ""}},
  {"human-vapor-1960", %{original: "ガス人間㐧1号", transliteration: "", translation: ""}},
  {"i-am-a-hero-2016", %{original: "アイアムアヒーロー", transliteration: "", translation: ""}},
  {"invasion-of-astro-monster-1965", %{original: "怪獣大戦争", transliteration: "", translation: ""}},
  {"invisible-man-1954", %{original: "透明人間", transliteration: "", translation: ""}},
  {"jin-roh-the-wolf-brigade-2000", %{original: "人狼 JIN-ROH", transliteration: "", translation: ""}},
  {"juvenile-2000", %{original: "ジュブナイル", transliteration: "", translation: ""}},
  {"k-20-legend-of-the-mask-2008", %{original: "K-20 怪人二十面相・伝", transliteration: "", translation: ""}},
  {"kagemusha-1980", %{original: "", transliteration: "", translation: ""}},
  {"kaiji-2-2011", %{original: "", transliteration: "", translation: ""}},
  {"kaiji-2009", %{original: "", transliteration: "", translation: ""}},
  {"kamen-rider-the-first-2005", %{original: "", transliteration: "", translation: ""}},
  {"kamen-rider-the-next-2007", %{original: "", transliteration: "", translation: ""}},
  {"kamui-gaiden-2009", %{original: "", transliteration: "", translation: ""}},
  {"kikis-delivery-service-1989", %{original: "", transliteration: "", translation: ""}},
  {"king-kong-escapes-1967", %{original: "", transliteration: "", translation: ""}},
  {"king-kong-vs-godzilla-1962", %{original: "", transliteration: "", translation: ""}},
  {"l-change-the-world-2008", %{original: "", transliteration: "", translation: ""}},
  {"lake-of-dracula-1971", %{original: "", transliteration: "", translation: ""}},
  {"last-war-1961", %{original: "", transliteration: "", translation: ""}},
  {"latitude-zero-1969", %{original: "", transliteration: "", translation: ""}},
  {"legend-of-the-eight-samurai-1980", %{original: "", transliteration: "", translation: ""}},
  {"library-wars-2013", %{original: "", transliteration: "", translation: ""}},
  {"library-wars-the-last-mission-2015", %{original: "", transliteration: "", translation: ""}},
  {"living-skeleton-1968", %{original: "", transliteration: "", translation: ""}},
  {"lorelei-the-witch-of-the-pacific-ocean-2005",
   %{original: "", transliteration: "", translation: ""}},
  {"lost-world-of-sinbad-1963", %{original: "", transliteration: "", translation: ""}},
  {"lovedeath-2007", %{original: "", transliteration: "", translation: ""}},
  {"lupin-iii-the-castle-of-cagliostro-1979",
   %{original: "", transliteration: "", translation: ""}},
  {"lupin-the-3rd-2014", %{original: "", transliteration: "", translation: ""}},
  {"magic-serpent-1966", %{original: "", transliteration: "", translation: ""}},
  {"magnitude-7-9-1980", %{original: "", transliteration: "", translation: ""}},
  {"matango-1963", %{original: "", transliteration: "", translation: ""}},
  {"mechanical-violator-hakaider-1995", %{original: "", transliteration: "", translation: ""}},
  {"message-from-space-1978", %{original: "", transliteration: "", translation: ""}},
  {"moon-over-tao-1997", %{original: "", transliteration: "", translation: ""}},
  {"mothra-1961", %{original: "", transliteration: "", translation: ""}},
  {"mothra-vs-godzilla-1964", %{original: "", transliteration: "", translation: ""}},
  {"mushi-shi-2007", %{original: "", transliteration: "", translation: ""}},
  {"my-neighbor-totoro-1988", %{original: "", transliteration: "", translation: ""}},
  {"mysterians-1957", %{original: "", transliteration: "", translation: ""}},
  {"nausicaa-of-the-valley-of-the-wind-1984",
   %{original: "", transliteration: "", translation: ""}},
  {"new-tale-of-zatoichi-1963", %{original: "", transliteration: "", translation: ""}},
  {"oblivion-island-haruka-and-the-magic-mirror-2009",
   %{original: "", transliteration: "", translation: ""}},
  {"one-missed-call-2-2005", %{original: "", transliteration: "", translation: ""}},
  {"one-missed-call-2003", %{original: "", transliteration: "", translation: ""}},
  {"one-missed-call-final-2006", %{original: "", transliteration: "", translation: ""}},
  {"onmyoji-2001", %{original: "", transliteration: "", translation: ""}},
  {"onmyoji-ii-2003", %{original: "", transliteration: "", translation: ""}},
  {"orochi-the-eight-headed-dragon-1994", %{original: "", transliteration: "", translation: ""}},
  {"parasite-eve-1997", %{original: "", transliteration: "", translation: ""}},
  {"parasyte-part-1-2014", %{original: "", transliteration: "", translation: ""}},
  {"parasyte-part-2-2015", %{original: "", transliteration: "", translation: ""}},
  {"patlabor-2-the-movie-1993", %{original: "", transliteration: "", translation: ""}},
  {"patlabor-the-movie-1989", %{original: "", transliteration: "", translation: ""}},
  {"platinum-data-2013", %{original: "", transliteration: "", translation: ""}},
  {"ponyo-2008", %{original: "", transliteration: "", translation: ""}},
  {"porco-rosso-1992", %{original: "", transliteration: "", translation: ""}},
  {"princess-blade-2001", %{original: "", transliteration: "", translation: ""}},
  {"princess-mononoke-1997", %{original: "", transliteration: "", translation: ""}},
  {"prophecies-of-nostradamus-1974", %{original: "", transliteration: "", translation: ""}},
  {"rashomon-1950", %{original: "", transliteration: "", translation: ""}},
  {"rebirth-of-mothra-1996", %{original: "", transliteration: "", translation: ""}},
  {"rebirth-of-mothra-ii-1997", %{original: "", transliteration: "", translation: ""}},
  {"rebirth-of-mothra-iii-1998", %{original: "", transliteration: "", translation: ""}},
  {"red-spectacles-1987", %{original: "", transliteration: "", translation: ""}},
  {"rescue-wings-2008", %{original: "", transliteration: "", translation: ""}},
  {"return-of-daimajin-1966", %{original: "", transliteration: "", translation: ""}},
  {"return-of-godzilla-1984", %{original: "", transliteration: "", translation: ""}},
  {"returner-2002", %{original: "", transliteration: "", translation: ""}},
  {"ring-0-birthday-2000", %{original: "", transliteration: "", translation: ""}},
  {"ring-1998", %{original: "", transliteration: "", translation: ""}},
  {"ring-2-1999", %{original: "", transliteration: "", translation: ""}},
  {"rodan-1956", %{original: "", transliteration: "", translation: ""}},
  {"rurouni-kenshin-2012", %{original: "", transliteration: "", translation: ""}},
  {"rurouni-kenshin-kyoto-inferno-2014", %{original: "", transliteration: "", translation: ""}},
  {"rurouni-kenshin-the-legend-ends-2014", %{original: "", transliteration: "", translation: ""}},
  {"sakuya-slayer-of-demons-2000", %{original: "", transliteration: "", translation: ""}},
  {"samaritan-zatoichi-1968", %{original: "", transliteration: "", translation: ""}},
  {"samurai-commando-mission-1549-2005", %{original: "", transliteration: "", translation: ""}},
  {"samurai-i-musashi-miyamoto-1954", %{original: "", transliteration: "", translation: ""}},
  {"samurai-ii-duel-at-ichijoji-temple-1955",
   %{original: "", transliteration: "", translation: ""}},
  {"samurai-iii-duel-at-ganryu-island-1956",
   %{original: "", transliteration: "", translation: ""}},
  {"samurai-reincarnation-1981", %{original: "", transliteration: "", translation: ""}},
  {"sanjuro-1962", %{original: "", transliteration: "", translation: ""}},
  {"sayonara-jupiter-1984", %{original: "", transliteration: "", translation: ""}},
  {"secret-of-the-telegian-1960", %{original: "", transliteration: "", translation: ""}},
  {"seven-samurai-1954", %{original: "", transliteration: "", translation: ""}},
  {"shin-godzilla-2016", %{original: "", transliteration: "", translation: ""}},
  {"shinobi-heart-under-blade-2005", %{original: "", transliteration: "", translation: ""}},
  {"sinking-of-japan-2006", %{original: "", transliteration: "", translation: ""}},
  {"sky-crawlers-2008", %{original: "", transliteration: "", translation: ""}},
  {"sky-high-2003", %{original: "", transliteration: "", translation: ""}},
  {"son-of-godzilla-1967", %{original: "", transliteration: "", translation: ""}},
  {"space-amoeba-1970", %{original: "", transliteration: "", translation: ""}},
  {"space-battleship-yamato-2010", %{original: "", transliteration: "", translation: ""}},
  {"spiral-1998", %{original: "", transliteration: "", translation: ""}},
  {"spirited-away-2001", %{original: "", transliteration: "", translation: ""}},
  {"stand-by-me-doraemon-2014", %{original: "", transliteration: "", translation: ""}},
  {"stray-dog-kerberos-panzer-cops-1991", %{original: "", transliteration: "", translation: ""}},
  {"submersion-of-japan-1973", %{original: "", transliteration: "", translation: ""}},
  {"sword-of-alexander-2007", %{original: "", transliteration: "", translation: ""}},
  {"tale-of-zatoichi-1962", %{original: "", transliteration: "", translation: ""}},
  {"tale-of-zatoichi-continues-1962", %{original: "", transliteration: "", translation: ""}},
  {"talking-head-1992", %{original: "", transliteration: "", translation: ""}},
  {"terror-of-mechagodzilla-1975", %{original: "", transliteration: "", translation: ""}},
  {"tetsujin-28-2005", %{original: "", transliteration: "", translation: ""}},
  {"three-outlaw-samurai-1964", %{original: "", transliteration: "", translation: ""}},
  {"three-treasures-1959", %{original: "", transliteration: "", translation: ""}},
  {"throne-of-blood-1957", %{original: "", transliteration: "", translation: ""}},
  {"tokyo-blackout-1987", %{original: "", transliteration: "", translation: ""}},
  {"top-secret-murder-in-mind-2016", %{original: "", transliteration: "", translation: ""}},
  {"triumphant-return-of-general-rouge-2009",
   %{original: "", transliteration: "", translation: ""}},
  {"tsubaki-sanjuro-2007", %{original: "", transliteration: "", translation: ""}},
  {"ultraman-the-next-2004", %{original: "", transliteration: "", translation: ""}},
  {"vampire-doll-1970", %{original: "", transliteration: "", translation: ""}},
  {"varan-the-unbelievable-1958", %{original: "", transliteration: "", translation: ""}},
  {"versus-2000", %{original: "", transliteration: "", translation: ""}},
  {"war-in-space-1977", %{original: "", transliteration: "", translation: ""}},
  {"war-of-the-gargantuas-1966", %{original: "", transliteration: "", translation: ""}},
  {"warning-from-space-1956", %{original: "", transliteration: "", translation: ""}},
  {"whirlwind-1964", %{original: "", transliteration: "", translation: ""}},
  {"wind-rises-2013", %{original: "", transliteration: "", translation: ""}},
  {"wrath-of-daimajin-1966", %{original: "", transliteration: "", translation: ""}},
  {"x-from-outer-space-1967", %{original: "", transliteration: "", translation: ""}},
  {"yojimbo-1961", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-1989", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-and-the-chess-expert-1965", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-and-the-chest-of-gold-1964", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-and-the-doomed-man-1965", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-and-the-fugitives-1968", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-at-large-1972", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-challenged-1967", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-goes-to-the-fire-festival-1970",
   %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-in-desperation-1972", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-meets-the-one-armed-swordsman-1971",
   %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-meets-yojimbo-1970", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-on-the-road-1963", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-the-fugitive-1963", %{original: "", transliteration: "", translation: ""}},
  {"zatoichi-the-outlaw-1967", %{original: "", transliteration: "", translation: ""}},
  {"zatoichis-cane-sword-1967", %{original: "", transliteration: "", translation: ""}},
  {"zatoichis-conspiracy-1973", %{original: "", transliteration: "", translation: ""}},
  {"zatoichis-flashing-sword-1964", %{original: "", transliteration: "", translation: ""}},
  {"zatoichis-pilgrimage-1966", %{original: "", transliteration: "", translation: ""}},
  {"zatoichis-revenge-1965", %{original: "", transliteration: "", translation: ""}},
  {"zatoichis-vengeance-1966", %{original: "", transliteration: "", translation: ""}},
  {"zeiram-1991", %{original: "", transliteration: "", translation: ""}},
  {"zeiram-1994", %{original: "", transliteration: "", translation: ""}}
]
